version: "3.9"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    container_name: empire_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./empire.db:/app/empire.db
    restart: always

  bailey:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: bailey_client
    depends_on:
      - gateway
    volumes:
      - ./bailey-cloud/auth:/app/auth
    restart: always
